### ISSUE TITLE
Remove Module

### ISSUE THREAD

**Issue by drinkingsouls** [yireo/Yireo_Webp2#105]
Hi, this module puts extreme strain on the CPU by generating images on the fly.
I'm trying to remove it from my site. I have it disabled and have deleted the directory for it but it's still showing as installed:

Yireo_NextGenImages
Yireo_Webp2

php7.4 bin/magento module:uninstall Yireo_NextGenImages sticks when I try to run it.
How can I remove all references of this?
Thank you.

**Comment by jissereitsma** [comment]
Removing these modules is no different from removing other modules from Magento 2: I trust that you know about the principles of DI compilation and caching. So, remove the files, wipe the cache, regenerate the DI files and you're done.

I'm not sure what you say with "showing as installed". If you refer to the `app/etc/config.php` file, remove those lines manually. 

If you run the `module:uninstall` command, you supply the `composer` name, not the Magento module name. It should never be run on production, because it conflicts with your deployment chain. So in general, what any professional Magento dev does is: Remove the files from composer, commit the composer lock and json to git, push, pull on production, run composer install, run setup upgrade, run DI compile, flush cache, swap shadow from production env and all of that based on a proper tool like Capistrano or similar. You scare me if you say that you're running `bin/magento module:uninstall` on a Magento module name, and then saying it "sticks".

What additional references are you referring to?

All of the above are generic Magento instructions. Write them down because they apply to any Magento module. And please note that your question is therefore much more a thing to place on a general Magento support forum, then a request for help with these specific modules.

As a comment on the CPU usage: It is a simple calculation. If you have 10.000 JPEGs in your normal catalog and you deliberately use this module to generate WebP images out of them, it is going to cost you CPU power. No surprise here. The module allows you to skip WebP generation if you're using another tool (Node, GoLang, whatever) to generate those WebP images (which will also cost you CPU power). So the comment that this module puts strain on the CPU is actually a logical thing. Also note that there were issues fixed in the past, so I assume you already tried upgrading to the latest version instead of bluntly saying that it didn't work. It is your job as a system integrator to determine whether the CPU strain of generating new WebP image is better or worse than having large JPGs for all devices even though WebP is supported.
