### ISSUE TITLE
Product page duplicating images

### ISSUE THREAD

**Issue by phes71** [yireo/Yireo_Webp2#108]
In the product admin we have two different images

But on the product page it shows the first image twice and the second image is missing

The url to the jpg shows the expected image
cache/a35feaac9df764e89b33b339cfadd4b6/3/1/31610.jpg
but the wbp files dosnt match
/cache/a35feaac9df764e89b33b339cfadd4b6/3/1/31610.wbp

**Comment by jissereitsma** [comment]
With this little information, it is hard to say anything. For instance, this extension actually creates a file suffix `webp` instead of `wbp`. And is this folder writable? And what about the troubleshooting docs in this repository that get you started? The more you can be more proactive, the more free support from others like me pays off.

**Comment by jissereitsma** [comment]
Great that you mentioned this. Indeed it seems to be the issue and it's actually already addressed in another issue here: https://github.com/yireo/Yireo_Webp2/issues/76 and https://github.com/yireo/Yireo_Webp2/issues/88 (I can't recommend the solution in the last ticket because it will be totally different from the next release). I'll close this ticket for now as a duplicate. The other issue mentions that a solution is underway.
