### ISSUE TITLE
Empty image issue

### ISSUE THREAD

**Issue by shyopat** [yireo/Yireo_Webp2#138]
Hi ,

we are getting issue:
Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Empty input file in vendor/rosell-dk/webp-convert/src/Convert/Converters/Gd.php on line 219

but image exist on this location.

Plz check the same.

**Comment by jissereitsma** [comment]
Unfortunately, this is not something to easily duplicate, because it is specific to your images and to your PHP version. First, make sure to upgrade your GD libraries and your PHP version to the latest version. Possibly also update things like Imagick on your server. Next, check your JPEG images for invalid input. Perhaps it is your PHP. Perhaps it is one of the images that is actually broken.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity. Feel free to reopen if needed.
