### ISSUE TITLE
Product's main image doesn't open or zoom

### ISSUE THREAD

**Issue by ameerpotrik** [yireo/Yireo_Webp2#141]
On the product page when we click on the Main image, it doesn't zoom. From top to bottom, when we attempt to click the thumbnail image it shows up as the main image and when we again click on it, it doesn't open or zoom.
Out of all the thumbnail images, only the last one is able to open and zoom.

Below is the screen recording of the demonstration to give clarity on this issue.
https://www.loom.com/share/c2ba1c2758674fe9b330273f4c7fa901

**Comment by jissereitsma** [comment]
Let me first make sure this ticket makes sense. One thing that you didn't mention here is that you are using Hyva as a theme. Please make sure to report this everywhere where you are posting issues, because Hyva is not Magento and Magento is not Hyva. If you are experiencing theming issues with a specific theme, it definitely makes sense to mention that theme to the very least.

Also, please mention your Magento version, PHP version, WebP extension version, WebP compatibitility extension version and last but not least, report the JavaScript errors in your console.

Make sure to realize that this is voluntary support you are asking for. With Hyva, you are paying for a license so you could say that you are buying in support hours. For any other open source extension out there, like this one, you are not paying any money, so are relying upon voluntary support. Because of this, you can only ask others to help out if you yourself already go into every way possible to ease solving the issue. As of yet, I don't see much technical details here and/or evidence that you have investigated things on a technical level. Please help me help you.

**Comment by ameerpotrik** [comment]
Hello @jissereitsma, here are the details

Magento Version: 2.4.5.
PHP version: 8.1.13
Hyva Theme Version - 1.2.1
WebP2 Module version: 0.12.4
NextGenImages Module version:  0.3.12

I hope the loom recording attached to the issue will help or may give you some hints to investigate things to a certain extent. There are no errors in the console which is making the scenario a bit difficult to identify what is causing it. Your assistance will help us identify the issue and knock it off. Thanks in advance!

**Comment by Tanu098** [comment]
Try to downgrade the versions of
WebP2 Module version: 0.12.4 to 0.12.2
NextGenImages Module version: 0.3.12 to 0.3.10

**Comment by jissereitsma** [comment]
Currently, WebP and NextGenImages support Hyva out of the box. Could you upgrade to the latest release? If this is still an issue, feel reopen this issue. But note that the current releases should not have issues with the product gallery any more. If they do, it might be related to something in your specific shop.
