### ISSUE TITLE
Does this really adds WebP support to Magento 2?

### ISSUE THREAD

**Issue by bfontaine** [yireo/Yireo_Webp2#160]
Hello,
I’m looking for a module that adds WebP support to Magento 2, so that one can upload WebP images along JPG and PNG ones. However, from what I see this module doesn’t do that; it adds some auto-conversion of PNG/JPG images to WebP, which is a different thing than adding actual support for the format in Magento.
Is this right or did I miss something?

**Comment by kestraly** [comment]
@bfontaine - It auto converts PNG/JPG images on a page

**Comment by jissereitsma** [comment]
@bfontaine As @kestraly already pointed out, this extension its functionality is to convert images, not to fix the Magento core. Realize that uploading a WebP image is only a thing of a file uploader - you also want the core to resize, crop, thumbnail etcetera. That's something that needs to be done in the core, not by adding modules. If you haven't already, do make sure to open an **Issue** in the Magento repository for this feature request. As of yet, because this module does not have the purpose that you describe, I'm closing this ticket.
