### ISSUE TITLE
Problem with svg format images 

### ISSUE THREAD

**Issue by maya5510** [yireo/Yireo_Webp2#165]
I have already installed this module on Magneto2.3.4 only using GD extension and it is working for .jpg and .png images. But for .svg images dooes somethning like this:
```

<source type="image/webp" srcset="https://wymienolej.pl/static/version1717697891/frontend/vagwan/wowo/pl_PL/images/wologo16.svg.webp">
<img src="https://wymienolej.pl/static/version1717697891/frontend/vagwan/wowo/pl_PL/images/wologo16.svg" title="wymienolej.pl" alt="wymienolej.pl" width="400" height="92" loading="lazy">
``` 
So it should delete ".svg" from webp version of link. Or it can be problem with location of this svg files ? They are located in app/design.
```
Unable to resolve the source file for 'frontend/vagwan/wowo/pl_PL/images/wologo16.svg.webp'
<pre>#1 Magento\Framework\App\StaticResource->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#2 Magento\Framework\App\Bootstrap->run() called at [pub/static.php:13]
</pre>
```

**Comment by jissereitsma** [comment]
Which version of this module are you then using? And which version of the Yireo NextGenImages module? As far as I do there are matches to replace images ending with `jpg`, `png` or similar. But SVG images are **not** dealt with by this module.

**Comment by maya5510** [comment]
PHP 7.3.22-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  9 2020
06:46:30)
Magento2.3.4
"name": "yireo/magento2-next-gen-images",
"version": "0.4.0",
"name": "yireo/magento2-webp2",
"version": "0.13.5",

I can enable the module on my production site www.wymienolej.pl and you can
take a look. All svg image are in tag <img src="image.svg"> and the folder
path is:
/var/www/magento2/app/design/frontend/vagwan/wowo/web/images

pt., 7 cze 2024 o 08:41 Jisse Reitsma ***@***.***> napisał(a):

**Comment by jissereitsma** [comment]
Thanks. It could be a bug that is already fixed years ago. Could you first upgrade to the latest version of `yireo/magento2-next-gen-images`?

**Comment by maya5510** [comment]
I have installed this modules by composer yesterday, how do a upgrade ?

pt., 7 cze 2024 o 12:58 Jisse Reitsma ***@***.***> napisał(a):

**Comment by jissereitsma** [comment]
If you installed it yesterday, but are running still Magento 2.3.4 (which got its last updates in 2020), it means you are also running the modules that were compatible with Magento four years ago. Four years is a long time. First update Magento, then fix the modules that run on top of it. Or merge the diffs between module versions yourself. But as an extension developer I can only fix bugs by releasing upgrades, not by remaining compatible with software that is dangerously outdated. I'm closing this issue as of yet, because there is little to report - except for that you are reporting that your Magento instance has severe issues.
