### ISSUE TITLE
not working on magento 2.3.3

### ISSUE THREAD

**Issue by jackeyleexm** [yireo/Yireo_Webp2#18]
hello,
   i installed 0.4.6 version.   on our magento 2.3.3 ,but the are processes blocked and my account reaches the limit of my resources.What is the reason for this? Which version is suitable for magento 2.3.3? Pls help me.

Regards,
Jackey

**Comment by jissereitsma** [comment]
It seems your hosting provider is restricting resources. How did they
respond to this support request?

**Comment by jackeyleexm** [comment]
hello,
  My hosting provider told me as follow:  
 ' You can contact a developer in order to fix the issue with the module. Or find a similar module that is not causing this issue.'

Regards.

**Comment by jissereitsma** [comment]
Thanks for the update. This is a pity because your hosting provider is in charge of putting limits to resources on your account. And to the very least, they should be able to respond for what kind of reason what kind of processes are blocked.

To clear up some confusion, our extension allows you to convert JPG images to WebP. Next, when a WebP image exists, our extension will update the HTML sources to use a `picture` element. Because the hosting provider is not able to respond in any helpful way, I'm guessing that they are restricting your Magento shop in such a ridiculous way that simple processes to convert images to WebP are denied.

Unfortunately, there is nothing I can do with this support request, because the hosting provider tells you that you can't generate WebP images on the fly, because they think you are not paying enough to receive the right amount of resources. Either demand a money-back from them, demand their support anyway or switch hosting provider.

Please note that the title of this issue is wrong and misleading: The extension works fine under Magento 2.3.3 but it caused your hosting provider to block resources for unknown reason. So a better title would have been "Extension causes account to be blocked"  or something. This extension works with 2.3.3 and is actually used on numerous 2.3.3 sites without issues. Your hosting account seems the limitation here.

**Comment by jissereitsma** [comment]
Yireo - Opening Up Technology

Yireo - Opening Up Technology


** Yireo tools that help you as a Magento agency
------------------------------------------------------------

Hi ,

While the main focus of Yireo has shifted over the years from custom projects to extensions to training, I do still actively develop numerous Magento extensions. And those extensions are both relevant to the technical merchant and the developer.

With a full agenda of remote online training (like the upcoming Vue Storefront 1 Fundamentals (https://www.yireo.com/training/2020-04-21-vuestorefront-basics?mc_cid=b967b5b24e&mc_eid=[UNIQID]) on April 28th/29th), I (and maybe you too) often overlook the fact that there is a wealth of tools that Yireo provides you (the agency) to increase your productivity.

Here is a listing of some (but not all) Yireo tools:


** General purpose tools
------------------------------------------------------------
* magento2-replace-all (https://github.com/yireo/magento2-replace-all?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Magento ships with dozens of extensions that you do not want and still clutter your shop. Let's replace them with nothing.
* Webp2 (https://github.com/yireo/Yireo_Webp2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Optimize JPEGs and PNGs by automatically turning them into WebP images.
* DisableServiceWorkerInAdmin (https://github.com/yireo/Yireo_DisableServiceWorkerInAdmin?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Disable (or actually unregister) any active service worker in the Magento Admin Panel. Mainly useful if your frontend serves a PWA.
* DisableLog2 (https://github.com/yireo/Yireo_DisableLog2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Prevent Magento from spending resources on writing database logs that you're not going to use anyway because you are using Google Analytics or something similar which is a lot better anyway.
* LinkPreload (https://github.com/yireo/Yireo_LinkPreload?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Add Link preload HTTP headers to your frontend and therefore speed up your site.


** Developer tools
------------------------------------------------------------
* AutoFlushCache (https://github.com/yireo/Yireo_AutoFlushCache?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Automatically refresh the configuration cache once you change something in your Store Configuration.
* Whoops (https://github.com/yireo/Yireo_Whoops?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Beautiful exception messages.
* DevHacks (https://github.com/yireo/Yireo_DevHacks?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Some hacks that I use daily in my own development environment.
* ExtensionChecker (https://github.com/yireo/Yireo_ExtensionChecker?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Validate if your extension code is following standards. For instance, it checks whether dependencies are declared in your XML and composer file.
* CheckoutTester2 (https://github.com/yireo/Yireo_CheckoutTester2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Easily test the checkout success page, without going through the checkout process again and again.


** GraphQL-specific developer tools
------------------------------------------------------------
* GraphQlRateLimiting (https://github.com/yireo/Yireo_GraphQlRateLimiting?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Prevent hackers from flooding your GraphQL API.
* CustomGraphQlQueryLimiter (https://github.com/yireo/Yireo_CustomGraphQlQueryLimiter?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Customize parameters of the GraphQL Query Limiter easily, thus preventing bad GraphQL queries from overloading your database.
* SyncGraphQlSessionWithFrontend (https://github.com/yireo/Yireo_SyncGraphQlSessionWithFrontend?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Make sure your GraphQL session and the regular frontend session are in sync.
* AdditionalEndpointsGraphQl (https://github.com/yireo/Yireo_AdditionalEndpointsGraphQl?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Some handy GraphQL endpoints like loading a single product, validating a token, loading all CMS pages.


** And, yes, some commercial ones as well
------------------------------------------------------------
* EmailTester2 (https://www.yireo.com/software/magento-extensions/emailtester2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Preview and test-send transactional emails with actual content.
* DeleteAnyOrder2 (https://www.yireo.com/software/magento-extensions/delete-any-order-2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Delete orders from the database safely, without leaving left-overs like some other extensions do.
* SalesBlock2 (https://www.yireo.com/software/magento-extensions/salesblock2?mc_cid=b967b5b24e&mc_eid=[UNIQID]) - Prevent certain orders from being placed, based on extensive rules that you manage in the backend.


** Serving as a tiger team for you as agency
------------------------------------------------------------

My main focus is training. And in that role, I'm helping out agencies on a weekly basis. However, besides training and education, there is more we can do: Setup integration testing and guide the team into using it, increase download performance by setting up a mirror of Magento Marketplace, setup a CI/CD chain and much more. Hopefully, the small listing of extensions above shows my commitment in making your business succeed.

Kind regards,
Jisse Reitsma
brain of Yireo
trainer of Magento developers
Magento Master "Mover" 2017-2018
creator of MageTestFest (https://magetestfest.com/?mc_cid=b967b5b24e&mc_eid=[UNIQID]) and Reacticon (https://reacticon.org?mc_cid=b967b5b24e&mc_eid=[UNIQID])
organizer of the Dutch Magento2Seminar (https://magento2seminar.yireo.com/?mc_cid=b967b5b24e&mc_eid=[UNIQID])
board member of ExtDN.org (https://extdn.org?mc_cid=b967b5b24e&mc_eid=[UNIQID])
gardening without any knowledge of plants

twitter: @yireo (https://twitter.com/yireo?mc_cid=b967b5b24e&mc_eid=[UNIQID]) / @jissereitsma (https://twitter.com/jissereitsma?mc_cid=b967b5b24e&mc_eid=[UNIQID])
facebook: facebook.com/yireo (https://www.facebook.com/yireo?mc_cid=b967b5b24e&mc_eid=[UNIQID])
linkedin: linkedin.com/in/jissereitsma (https://www.linkedin.com/in/jissereitsma?mc_cid=b967b5b24e&mc_eid=[UNIQID])
email: jisse@yireo.com (mailto:jisse@yireo.com)
Jisse Reitsma

You have been subscribed to this list, because we either did business together in the past, or you downloaded a Yireo extension from our site, or attended a Yireo training or event, or something else nice that we did together. I hope we don't annoy you. We mean no harm.

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://yireo.us2.list-manage.com/about?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06&c=b967b5b24e)     unsubscribe from this list (https://yireo.us2.list-manage.com/unsubscribe?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06&c=b967b5b24e)     update subscription preferences (https://yireo.us2.list-manage.com/profile?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06)
Yireo . Meent 29A . Soest, - 3762DX . Netherlands

**Comment by jissereitsma** [comment]
Yireo - Opening Up Technology

Yireo - Opening Up Technology


** Last call for Magento PWA Studio training (May 19th/20th)
------------------------------------------------------------

Hi ,

This is a last call towards Magento developers that are seeking to get more information on Magento PWA Studio: Next week, Tuesday 19th and Wednesday 20th, you can join our Magento PWA Studio training. It is remotely (logical in these times), it is cheap and it is unique (because I'm actually not sure if anyone else is offering professional Magento PWA Studio training at this moment).


** Why jump on board now?
------------------------------------------------------------

Magento PWA Studio is becoming more and more stable with every release. And everybody already knows that the current Magento frontend is outdated, not performing well and overly complicated: A new frontend (like built upon React) is simply making sense. And if you are agency, missing out on this trending technology is a waste.


** Training details
------------------------------------------------------------

The training starts on Tuesday in the morning (Central European time), ends in the early afternoon and starts again on Wednesday morning. During two half days, you will learn plenty on UPWARD, Venia theming, Peregrine's setup, underlying Apollo logic and much much more. And in the afternoons, you will have time play around with things. And whenever you might have questions, I'll be there to cover your back!

For more details see yireo.com/training/2020-05-19-magento-pwa-studio (https://www.yireo.com/training/2020-05-19-magento-pwa-studio?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])


** Custom training
------------------------------------------------------------

Perhaps the timing is not right, perhaps you are in a different time zone, perhaps you had another topic in mind. Do let me know if you are interested in other training: I've been training teams on a variety of topics - Magento frontend development, backend development, DevOps, React, GraphQL, Vue and much more.


** Other stuff I'm working on
------------------------------------------------------------

While I think Magento PWA Studio is an amazing solution, it is not for everyone. Because of this, I'm getting also more and more involved with the Vue Storefront community - offering training already for more than half a year and releasing more and more handy development tools. Additionally, I'm involved with various GraphQL initiatives, both with Magento and with other systems - Apollo Federation, slick Webpack configurations, microservices built in Node or stand-alone PHP frameworks like Slim, Docker-driven remote development environments and more.

It would be awesome if we can all keep growing towards faster frontends. Let me know if you have any questions.

Kind regards,
Jisse Reitsma
brain of Yireo
trainer of Magento, Vue and React developers
Magento Master "Mover" 2017-2018-2019
creator of MageTestFest (https://magetestfest.com/?mc_cid=9fdde4e4bc&mc_eid=[UNIQID]) and Reacticon (https://reacticon.org?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
organizer of the Dutch Magento2Seminar (https://magento2seminar.yireo.com/?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
board member of ExtDN.org (https://extdn.org?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
gardening without any knowledge of plants

twitter: @yireo (https://twitter.com/yireo?mc_cid=9fdde4e4bc&mc_eid=[UNIQID]) / @jissereitsma (https://twitter.com/jissereitsma?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
facebook: facebook.com/yireo (https://www.facebook.com/yireo?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
linkedin: linkedin.com/in/jissereitsma (https://www.linkedin.com/in/jissereitsma?mc_cid=9fdde4e4bc&mc_eid=[UNIQID])
email: jisse@yireo.com (mailto:jisse@yireo.com)
Jisse Reitsma

You have been subscribed to this list, because we either did business together in the past, or you downloaded a Yireo extension from our site, or attended a Yireo training or event, or something else nice that we did together. I hope we don't annoy you. We mean no harm.

This email was sent to reply@reply.github.com (mailto:reply@reply.github.com)
why did I get this? (https://yireo.us2.list-manage.com/about?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06&c=9fdde4e4bc)     unsubscribe from this list (https://yireo.us2.list-manage.com/unsubscribe?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06&c=9fdde4e4bc)     update subscription preferences (https://yireo.us2.list-manage.com/profile?u=e92389a6de3aeee127f0201d6&id=e8bc59e43b&e=fe6bb22d06)
Yireo . Meent 29A . Soest, - 3762DX . Netherlands
