### ISSUE TITLE
Not working with Fotorama

### ISSUE THREAD

**Issue by Eddcapone** [yireo/Yireo_Webp2#26]
I know you already made a notice in the wiki under "Usage"

> The Fotorama gallery of the Magento core product pages is replaced with WebP images, as long as the Full Page Cache is disabled. Unfortunately, with the FPC, the whole JavaScript needs to be refactored.

**Comment by jissereitsma** [comment]
I think this is actually already solved partially by the switch to a `<picture>` element in the past and the comment on Full Page Caching no longer applies - that code has been removed from this extension. I've updated the docs to recommend switching to Notorama: https://github.com/yireo/Yireo_Webp2/commit/0155ed1700e4d4bf46bdd99458bd42e18789c336

**Comment by Eddcapone** [comment]
Ok but the module you recommended has a warning

> This module is currently considered unstable and should not be used outside of development.

**Comment by jissereitsma** [comment]
True. There are numerous other replacements or options for product galleries. And from a performance standpoint, it is imply a very very healthy thing to investigate those options instead of keeping at the original Fotorama effect. It shows that Magento is human-work and not flawless. And therefore, it makes little sense to try to optimize a bad gallery solution with an additional WebP extension. The benefit will be low.
