### ISSUE TITLE
Very slow performance when using a CDN

### ISSUE THREAD

**Issue by GuiltyNL** [yireo/Yireo_Webp2#27]
Magento 2.3.3
PHP 7.3
NGINX 1.17
Bunny CDN

The Yireo Webp2 module is normally performing well on our server, but recently we started to test the Bunny CDN solution as we have international customers and they will benefit from CDN's throughout the World.

Bunny CDN is easy and straight forward to implement:

https://support.bunnycdn.com/hc/en-us/articles/360001944171-How-to-speed-up-your-Magento-website-with-BunnyCDN

However, when enabled like this, pages become real slow and when enabling the profiler we noticed a significant delay here:

`·  ·  ·  TEMPLATE:/Yireo_Webp2/templates/picture.phtml | 6.941191 SECONDS`

When we revert the cdn url to our own url, the Yireo Webp2 module is fast again.

Note that this slow performance is constantly, also when .webp alternative have been generated already. The module is also still functional and does serve .webp images with a .jpg as a backup.

Any thoughts?
 
P.S. Bunny CDN has a free 14 day trial. If needed.

**Comment by jissereitsma** [comment]
I'm not familiar with BunnyCDN and the blog that you mentioned only shows how things work from the Admin Panel point of view (magic) and not the actual technical approach. Are they using `picture` elements? Are they using only JavaScript? How are the URLs modified?

My WebP extension is simple in its approach: Scan the HTML source (as it is generated by Magento) for JPGs and then replace them with a `picture` element, so that there is a `source` in that `picture` also for WebP. And the WebP is then generated on the fly.

Unfortunately, I lack the time to pick up this task on a voluntary basis: It does not seem to be a generic issue in my extension and it seems to be related to a highly customized combination of extensions already. So this means that somebody needs to do a technical review of what goes wrong where and how the two extensions conflict. I would recommend to look past the profiling and do a code audit instead.

**Comment by GuiltyNL** [comment]
The technical approach is fairy simple. You have to change the URLs for /media and /static to the CDN url.

If they don't have a copy of the requested file on their servers they will fetch it from the original location, so normally the base url of Magento under /media and /static.

With the setup I've chosen at Bunny, they don't change anything within the served html. They only serve static content. Like Magento would do. It works like a mirror of the original location.

So you don't have to move or upload files to their server. They 'pull' a copy to their servers when they don't have it yet and serve it to the customer.

Bunny doesn't need additional software or extensions installed for Magento 2. You only need to change the urls and keep the original files in place.

We will review the code coming week and will let you know.

**Comment by GuiltyNL** [comment]
If you scan the HTML source, you will fetch the picture via the url mentioned? So you will fetch it from the CDN if enabled I guess? Or do you convert it to a server path? 

If it doesn't get converted guess the conversion tool gets the external CDN url too for the conversion? That may take extra time?

**Comment by jissereitsma** [comment]
No, that's not how this extension works. When a picture is scanned (JPG or PNG), the URL stripped, a simple check is done to see if the given picture exists within the Magento filesystem and when it does not, the picture is left alone. So when pictures are not found, no conversion is attempted either.

**Comment by GuiltyNL** [comment]
Hmm, noted. Thanks. I will dig into the code and this issue.

**Comment by GuiltyNL** [comment]
Issue has been addressed and solved. Our code hooked in to determine image sizes and did not strip the url, so it was requesting all the images from the CDN one at a time.

We stripped this now and all is working well again. The bug was on our side, sorry Jisse and thanks for your support.

**Comment by jissereitsma** [comment]
Glad to hear things are solved now. And thanks for the feedback!
