### ISSUE TITLE
Not modifying the HTML (Nginx + Varnish)

### ISSUE THREAD

**Issue by almr** [yireo/Yireo_Webp2#34]
Hello,

Webp images are generated already.
I'm trying to get the results but there is no HTML with <picture> generated as mentioned.
Is there is anything blocked by varnish cache?

Can you provide some solutions?

Thanks!

**Comment by jissereitsma** [comment]
Thanks for reporting. So you're saying that this extension does not work under Varnish. I have just spent 10 minutes to test this extension with a generic Varnish support. It works. It shows that you have spent too few time on reporting this and that this issue is related to your specific environment.

Please realize that this is a voluntary project. You have already gotten the software for free. But if you want support, either contact Yireo for paid support (where we will just charge our hours, no questions asked), or realize that placing a support request for free support also costs me time as well. In that way, please make sure you are adding more details, instead of requesting that I invest all this time into this. There are numerous details you can add, but I trust you are smart enough to come to this yourself.

Open source does not mean that you can claim somebody's time without investing your own.

**Comment by almr** [comment]
Thank you for replying me back. I just found that your code works well but in some places it doesn't replace the images tags. Issue is on theme side so I'll refine the code to get the desired results.

 I'll get back to you if I need.
Be careful!

**Comment by jissereitsma** [comment]
Closed because of inactivity
