### ISSUE TITLE
Enabling the module on Magento 2.2

### ISSUE THREAD

**Issue by kweij** [yireo/Yireo_Webp2#4]
I'm trying to install and enable this module, but I can't get it enabled.

It says in the install instructions:
> Enable the module by toggling the setting in Stores > Configuration > Advanced > System > Yireo WebP > Enabled
But that's no longer available in Magento 2.2.

The module checks for the config-value of `system/yireo_webp/enabled` to be `true` (or `1`), but that config field is not manageable from the backend.

Executing `bin/magento module:enable Yireo_Webp2` only updates the `app/etc/config.php`, enabling the module. Shouldn't that be enough? May the check on the `system/yireo_webp/enabled` config should be removed.

**Comment by jissereitsma** [comment]
That should be enough. I've just run a test under 2.2.7 and 2.3.1 and am seeing the section without issues. Also, the file `etc/adminhtml/system.xml` shows things are there.

**Comment by jissereitsma** [comment]
I've checked the version 0.3.0 (latest) release ZIP as well, and see now issues. Which version are you installing?

**Comment by kweij** [comment]
Oh, how silly. I've been looking in the wrong place of the configuration. I found it.

Magento 2.2.7, Yireo_Webp2 0.3.0

**Comment by oviliz** [comment]
Sorry I'm hijacking this @kweij / @jissereitsma, am I also looking into the wrong place?
![image](https://user-images.githubusercontent.com/73616/82157151-b39a8580-9877-11ea-951d-b9c75f639999.png)
![image](https://user-images.githubusercontent.com/73616/82157213-fc523e80-9877-11ea-87fa-e81be25093a7.png)
![image](https://user-images.githubusercontent.com/73616/82157225-05dba680-9878-11ea-82c9-0261a86d064b.png)
![image](https://user-images.githubusercontent.com/73616/82157246-2c014680-9878-11ea-9148-3fd8a8f7e51b.png)
![image](https://user-images.githubusercontent.com/73616/82157169-cf9e2700-9877-11ea-95c7-8ed074a7fff9.png)

**Comment by oviliz** [comment]
Actually, in the Support page say to look under Stores > Configuration > Yireo > Yireo WebP2, but that's not there in my case either...
https://github.com/yireo/Yireo_Webp2/blob/master/SUPPORT.md

**Comment by jissereitsma** [comment]
The original issue was closed already. When the original issue is solved, it would mean that either you can solve your issue as well, or it is a new issue. Next time, I would recommend you to open a new issue.

As being said earlier, I've run a test under 2.2.7 and 2.3.1 and am seeing the section without issues. Also, the file etc/adminhtml/system.xml shows things are there. So the issue is not related to the module, but somehow to your environment. Assuming that you have done the usual stuff (flushing the caching, making sure your admin role has all rights), I would say that this is an unknown issue caused by a configuration in your specific shop that somebody needs to troubleshoot.
