### ISSUE TITLE
Do not have effect homepaaaage but have effect on products pages

### ISSUE THREAD

**Issue by framesfashion** [yireo/Yireo_Webp2#46]
I install on my magento 2 develop site: d.framesfashion.com
it do not conver jpg to webp on home page https://d.framesfashion.com/
but it really conver products image to webp https://d.framesfashion.com/round-glasses-for-men-jt8019p-s.html
Could you please help to fix?

Thanks

**Comment by jissereitsma** [comment]
Thanks for reaching out. I did a scan of your HTML on both the homepage and the product pages. On both pages, I can see the `picture` element clearly in the HTML source. So I will close this ticket because there appears nothing wrong with this extension. This issue you are addressing does not apply to all images, so therefore, it is no longer a generic open source request, but instead a support request for your specific instance.

It could possibly be that something is wrong with your product images and/or PHP environment, causing some specific images to load and some others not. I'm happy to help out, but can't do this on a voluntary basis. Please send a mail to info@yireo.com if you are interested in paid support. Please note that that paid support is not meant for this extension (which works) but for support on your specific instance.

**Comment by framesfashion** [comment]
Thanks
