### ISSUE TITLE
Updating images trigger

### ISSUE THREAD

**Issue by Bashev** [yireo/Yireo_Webp2#54]
In some cases images are replaces/updated with new ones. if new images have same name (filename) as old one for example use sku for product image, their webp copy never will be updated.

May be on save need to be triggered regenerate of webp image.

**Comment by jissereitsma** [comment]
Thanks for asking. Actually, the extension is already checking for the modification time of the original image, which is the best the extension can do: https://github.com/yireo/Yireo_Webp2/blob/master/Image/File.php#L115 Could you shed some light on why this is not working for you? What filesystem are the images hosted on?

If you are saying that images are replaced or updated, what kind of trigger do you refer to? Because if the image is uploaded via FTP or something, then the trigger would not be within Magento but you will need to script your own solution. And if the image is uploaded in Magento, unfortunately there is no event for this in Magento.

**Comment by Bashev** [comment]
I'll make additional research and write with info and close issue (if no issue related to this module).

thank you for your time.
