### ISSUE TITLE
NWDThemes Revolution Slider

### ISSUE THREAD

**Issue by kestraly** [yireo/Yireo_Webp2#56]
Most recent update breaks revolution slider when regenerating the static/frontend content.

Disabling Webp2 extension resolves this.

Was working for a long time, however updated to the most recent version and it killed the slider. 

Would love to be able to exclude modules.

**Comment by jissereitsma** [comment]
Thanks for addressing this. Could you share some technical details also? You say it *breaks*, but what does it mean? Is your computer broken, does your OS give a white screen, or the browser, or is there an actual JavaScript error? Breaking is a word too general. Also, please note that our extension does nothing with static content deployment, there are no assets, so it seems strange that it would break while generating the static/frontend content. Are you referring to the command `bin/magento setup:static-content:deploy` or something else? And in which mode - Development and Production? Also, you mention that it kills the slider. Are you saying that you are unable to run static content deployment and still access the site in production with a broken slider? Because normally, without static content deployment, you are unable to use the entire site.

Last but not least, what do you mean with excluding modules? Should the WebP extension not be enabled if the revolution slider is enabled? Or do you mean that you want to skip WebP on specific pages (which is already in the docs)?

**Comment by kestraly** [comment]
Hi @jissereitsma,

I appreciate you reaching out. So the issue comes when running bin/magento setup:static-content:deploy.

The following directory becomes unstable, but I couldn't pin point why.
pub/static/frontend/Alothemes/default/en_US/Nwdthemes_Revslider/public/assets

Deleting the directory prevents the revolution slider from disappearing. I thought it was caused by dummy.png, however the problem was only resolved when the entire directory was deleted.

Apologies for my lack of clarity, it had taken a few days and couldn't figure out why it would sporadically stop working suddenly, but work again if clear static button in cache management was pressed.

**Comment by kestraly** [comment]
No issues with version 0.7.2

**Comment by jissereitsma** [comment]
Still, I'm unable to filter out the actual problems from what you say.

First, the issue comes from `setup:static-content:deploy` and you said it is unstable. What does "unstable" mean? In my 5 years of experience with Magento 2, I've never heard somebody say that this command line output becomes unstable. What is the exact error that you are seeing when running this command?

Suddenly, you have described a new problem as well: The slider disappears. Are there any JavaScript errors in the console?

I would like to clear things up by summing up the current issues:

1) The static content deploy command becomes unstable. What does this mean? With which error does the command fail?

2) The revolution slider disappears. Are there any JavaScript errors in the console?

3) The revolution slider breaks. Is there a crack in the slider? Or a JavaScript error? Or is this the same as point 2?

4) A dummy.webp has been created and is causing issues. Could you confirm that the dummy.webp image actually exists?

**Comment by kestraly** [comment]
You may not have heard someone say unstable, however that's exactly what the homepage did after recompiling. It became unstable and fixing it by deleting the dummy.png and dummy.webp images from the static directory allowed the home page banners to load again. There is no error during the compilation process.

Javascript error appears undefined property of bg for NWDslider.

This in turn causes the whole slider to fail during the page load process.

dummy.webp does appear in static content along with dummy.png. dummy.png is a file used by the NWD Slider.

I've not had much time to debug this further unfortunately

**Comment by jissereitsma** [comment]
I understand that you were trying to describe your problem with words, but if you are working with words like **unstable** and describe a problem **when regenerating the static/frontend content**, this leads to me thinking that there is something unstable about the deployment and that the command for static content deployment failed. I would urge to stick to the words available in the context. As far as I can see, you are unable to troubleshoot this yourself, while the only thing that you **can** see is an error `Javascript error appears undefined property of bg for NWDslider.`. Only after me pressing for details, you mentioned this JavaScript error. Please, could you simplify things in the future by reporting the errors that you see, and not introducing new terminology?

As I can see currently, there is a JavaScript error in some kind of third party extension. Have you reported this to them already? Because their extension is causing an issue. It might be related to ours. But they know their code better than you or I do? You purchased the extension with them. Does that not buy you support time?

I checked their demo and it is not mentioning a `dummy.png` image anywhere. How am I able to verify this?

**Comment by kestraly** [comment]
Support ran out as I was reporting this issue to them. Always the way.

Error: Uncaught TypeError: Cannot read property ‘bg’ of undefined

dummy.png existance as follows when it appears lazy loading is enabled.

```
if($lazyLoad != 'none'){
                                $imageAddParams .= ' data-lazyload="'.$urlSlideImage.'"';
                                $urlSlideImage = Framework::$RS_PLUGIN_URL.'public/assets/images/dummy.png';
                        }
```

```
if($lazyLoad != 'none' || $do_ll == 'force' && $do_ll !== 'ignore'){
                                                $seo_opti = RevSliderFunctions::getVal($layer, 'seo-optimized', false);
                                                if($seo_opti === 'false' || $seo_opti === false){
                                                        $imageAddParams .= ' data-lazyload="'.$urlImage.'"';
                                                        $urlImage = Framework::$RS_PLUGIN_URL."public/assets/images/dummy.png";
                                                }else{
                                                        $additional .= ' class="forceseo"';
                                                }
                                        }
```

I'm going to guess that the breakage is caused because IMG is caused in the following manner

 `$html = '<img src="'.$urlImage.'" alt="'.$alt.'"'.$additional.$imageAddParams.' data-no-retina>';`

Again, appreciate you taking the time to respond. I suspect that turning off lazy loader in the slider may resolve this issue entirely. I'll test this and get back to you.

**Comment by kestraly** [comment]
Disabled lazy loading on the slide, but same error. I'll disable WebP on the home page because it works perfectly everywhere else.

Uncaught TypeError: Cannot read property 'bg' of undefined
    at b (rs6.min.js:1)
    at y (rs6.min.js:1)
    at u (rs6.min.js:1)
    at rs6.min.js:1

**Comment by kestraly** [comment]
Seems to be fixed in most recent 0.9.5

**Comment by Garde85** [comment]
@kestraly I have the same problem. 

For some unknown reasons, my sliders created this dummy.webp image instead of right source image? Did you find a solution about this issue?

Thank you

**Comment by Garde85** [comment]
@jissereitsma i understood why this issue happens!

If in Revolution Slider 5 you if you apply specific settings to a slide, or to layers of a slide, Revolution Slider generate this kind of code for images:

`<img src="https://local.example.it/static/versionXXXX/frontend/example/exampleTheme/it_IT/Nwdthemes_Revslider/public/assets/images/dummy.png" alt="" data-ww="['267px','267px','267px','153px']" data-hh="['533px','533px','533px','305px']" data-lazyload="https://local.example.it/media/revslider/example-image.png" data-no-retina> </div>`

As you can see, Revolution Slider create 2 attribute:

- **src** that contains our wrong dummy image url
- **data-lazyload** that contain the right image url
 
but \Yireo\NextGenImages\Image\HtmlReplacer::replaceImagesInHtml only search attribute **src** and **data-src** as url source of images, then in this case Yireo_NextGenImages takes src attribute as good to be used ot generate webp tags, and this is the reason of our issue.

It could be possible to include data-lazyload in 
```

\Yireo\NextGenImages\Image\HtmlReplacer::replaceImagesInHtml 

        $regex = '/<([^<]+)\ (data\-src|src)=\"([^\"]+)\.(png|jpg|jpeg)([^>]+)>(\s*)<(\/?)([a-z]+)/msi';
```

as possible attribute to be used as source of images?
