### ISSUE TITLE
Incorrect URL in Magento v2.4.1 

### ISSUE THREAD

**Issue by AbdulSamadAbbasi** [yireo/Yireo_Webp2#59]
_convert_ function of class _Convertor.php_ returns incorrect URL after _resolve_ function call for example at below line :
`        $sourceImageFilename = $this->imageFile->resolve($sourceImageUrl);
`
_$sourceImageFilename_ contains URL path as "/var/www/html/magento241/pub/magento241/pub/media/wysiwyg/home/home-main.jpg" instead of "/var/www/html/magento241/pub/media/wysiwyg/home/home-main.jpg". Can someone else clarify this? Thanks and good extension, great work.

**Comment by jissereitsma** [comment]
Thanks for reporting this. Personally, I don't get the same results. So let's try to see what is different: Which OS are you using? Which PHP version? Which version of both the WebP extension and the NextGenImages extension?

**Comment by AbdulSamadAbbasi** [comment]
Thanks for response. My OS Ubuntu 16.04, PHP 7.4.11, WebP extension 0.9.5, NextGen extension 0.0.5. I'm attaching screenshot of echoing _$sourceImageFilename_ just after _resolve_ function call in _convert()_. If I give path manually for an image, it works but on page load it loads both _jpg_ and _webp_ images. Shouldn't it be only _webp_? Also I'm struggling to understand the purpose of _isNewerThan()_ . 
![error](https://user-images.githubusercontent.com/38076752/105017656-d95ed680-5a65-11eb-814d-d1e7c8c736f1.png)

**Comment by jissereitsma** [comment]
You have posted already another issue, showing that you got a step further with testing things. Could you let me know how you fixed this issue?

**Comment by AbdulSamadAbbasi** [comment]
Yes, I caught it in `getAbsolutePath()` method. The passed `sourceImageUrl` and the `getRoot()` both have one thing common i-e in my case `getRoot()` reutrns `\var\www\html\magento241` and the 'sourceImageUrl' passed also contained `magento241`. Sp I removed one and it was solved.

**Comment by jissereitsma** [comment]
Actually, by looking at your pathing (using backslashes instead of forward-slashes), it could be that you are using Windows? Is that indeed the case? Because if so, it would explain for things maybe. I'm still trying to duplicate something, but am unable to, which makes troubleshooting nearly impossible.

**Comment by AbdulSamadAbbasi** [comment]
Sorry, that was my mistake, I'm on Ubutnu and those slashes are forward ones. Actually now, I'm generating webp with script command and not on the fly, so I'm not using `resolve()` from where this error emerged. and if anyone else hasn't faced this issue, maybe it was to do something with my machine?

**Comment by jissereitsma** [comment]
I've heard about these kind of problems - where a Magento URL suddenly ends up to be a Magento absolute path - is occurring often when there are issues with file permissions. For instance, during the installation or simply when trying to write cache files. Fixing permissions is often the solution.

I'm closing this ticket as for now, because I'm unable to duplicate this and no one else is reporting this (yet). Feel free to comment if you still find anything.
