### ISSUE TITLE
not working on Magento 2.3.2 + Infortis/Ultimo theme

### ISSUE THREAD

**Issue by pieterpoorthuis** [yireo/Yireo_Webp2#6]
I'm running PHP 7.2 / Magento 2.3.2 / Infortis_Ultimo 2.8.1

I installed Yireo_Webp2 v0.3.0 via composer and enabled the module.
Running webp 1.0.2

There are three issues that show on my website, probably related:
1) Some images are returned as webp, but not all. Products that are selected on the fly by our theme are returned as png (instead of webp). We use this on-the-fly feature to automatically display products with the best price.
2) Some of the on-the-fly displayed products have two images (front + back). Without Yireo_Webp2, the image shows the back of the product when hovering over it. With Yireo_Webp2 both images are shown when the page is done loading.
The HTML source shows:
```
<div class="product-item-img">
   <a href="https://www2.bitgild.com/krugerrand-1oz-gold-mixed-years" class="product photo product-item-photo" style="max-width:265px;">
      <img class="product-image-photo lazyOwl" alt="Krugerrand, 1oz Gold, mixed years" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png.png" style="display: block;">
      <picture>
         <source srcset="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.webp" type="image/webp">
         <source srcset="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" type="image/png">
         <img src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" alt="Krugerrand, 1oz Gold, mixed years">
      </picture>
   </a>
</div>
```
When I disable the Yireo module, the HTML looks like this:
```
<div class="product-item-img">
   <a href="https://www2.bitgild.com/krugerrand-1oz-gold-mixed-years" class="product photo product-item-photo" style="max-width:265px;">
   <img class="product-image-photo lazyOwl" alt="Krugerrand, 1oz Gold, mixed years" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png.png" style="display: block;">
   <img class="alt-img" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" alt="Krugerrand, 1oz Gold, mixed years" style="display: none; opacity: 1;">                                
   </a>
</div>
```
3) When selecting one of the on-the-fly displayed products, the store directs me to the product page. The product page shows a big error:
"There has been an error processing your request
/var/www/bitgild/pub/hk/flat/16.png is not found"

When disabling Yireo_Webp2 (module:disable), the product page renders 100% ok again.

The following is a screenshot of my Yireo M2 config
![Webp2_M2_config](https://user-images.githubusercontent.com/13945200/60728779-6fddac80-9f41-11e9-94fc-bca4aece5df3.png)

My server is IP blocked. If you want access, please PM me your IP address.

**Comment by jissereitsma** [comment]
Thanks for opening up an issue. You mention that you are running WebP version 1.0.2. What are you referring to? A library? A `cwebp` binary? Our module has a different versioning which is shown in your screenshot?

Regarding the issues: 

1. You say that some images are returned as WebP. This actually proves that maybe the extension is working after all. But maybe the images that are not converted are simply incompatible with WebP in itself? Did you try to convert exactly those images using a different online WebP convertor, or a command-line `cwebp` conversion?

2. What is the actual issue here? You are just described that our Yireo_Webp2 extension indeed uses HTML `picture` to solve the problem, as this a modern standard to offer multiple images to different browsers, so that you but the browser determines which image to use. Or are you raising a question on the behaviour of the HTML `picture`? Or are you disagreeing with how `picture` should work? What is the actual issue here?

3. What is an on-the-fly displayed products? Is it simply a product being displayed or is it a generated product on the fly? Regarding the error, is the image `/var/www/bitgild/pub/hk/flat/16.png` a valid file or isn't it? And if it is not, what is the actual path then to this image called `16.png`?

As for the offer to jump up and fix the issue right away in your shop, probably a lot of hassle is needed with IP restriction being the least of worries. For instance, thorough troubleshooting requires SSH acces, and a proper inspection of all of the modules installed and much much more. As of yet, I need to decline this offer of additional voluntary work. The extension works in most cases. It also works in your shop (which issue 2 actually proves) but it doesn't work with all of your images, which might depend on numerous issues but starting with the possibility that those images can actually not be converted to WebP at all (https://github.com/yireo/Yireo_Webp2/blob/master/FAQ.md). And the last issue (3) tells me that some image path is non-standard in your Magento shop, proving that it is an issue not just related to Magento + our WebP extension, but specific to the customization you have done on this site (with modules, themes and custom work combined in a delicate combination). Hopefully my questions already lead you into the proper troubleshooting.

**Comment by pieterpoorthuis** [comment]
> You mention that you are running WebP version 1.0.2. What are you referring to? A library? A cwebp binary? Our module has a different versioning which is shown in your screenshot?

I downloaded the source from https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.0.2.tar.gz . Compiled & installed it. Running `cwebp -version` returns `1.0.2`


> You say that some images are returned as WebP. This actually proves that maybe the extension is working after all. But maybe the images that are not converted are simply incompatible with WebP in itself? Did you try to convert exactly those images using a different online WebP convertor, or a command-line cwebp conversion?

Yes, manually running cwebp from the CLI yields the following two files (btw: love the 88% compression ;) )
```
118776 Jun 13 13:48 krugerrand-1oz-gold-mixed-years-png.png
13616 Jul  8 11:53 krugerrand-1oz-gold-mixed-years-png.webp
```

> What is the actual issue here? 

Two main issues:
1) from the following HTML the first image is not converted into webp. There's no <picture> tag created, whereas the png image can be converted by cwebp (as demonstrated above).
```
<div class="product-item-img">
   <a href="https://www2.bitgild.com/krugerrand-1oz-gold-mixed-years" class="product photo product-item-photo" style="max-width:265px;">
   <img class="product-image-photo lazyOwl" alt="Krugerrand, 1oz Gold, mixed years" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png.png" style="display: block;">
   <img class="alt-img" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" alt="Krugerrand, 1oz Gold, mixed years" style="display: none; opacity: 1;">                                
   </a>
</div>
```
2) Yireo webp removes the styling from the image tags, causing the images to show incorrectly:
With Yireo webp:
```
<picture>
         <source srcset="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.webp" type="image/webp">
         <source srcset="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" type="image/png">
         <img src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" alt="Krugerrand, 1oz Gold, mixed years">
      </picture>
```

Without Yireo webp: 
`<img class="alt-img" src="https://www2.bitgild.com/media/catalog/product/cache/554df3bf679961be3dafe5cfde527fb2/k/r/krugerrand-1oz-gold-mixed-years-png-2.png" alt="Krugerrand, 1oz Gold, mixed years" style="display: none; opacity: 1;">`
The class and style tags are not present anymore in the <picture> tag

Hope this clarifies what's happening

**Comment by jissereitsma** [comment]
Issue 2 is fixed in https://github.com/yireo/Yireo_Webp2/commit/8c39b3f8a39ae05917193e987e9639586ee92b77

**Comment by jissereitsma** [comment]
The mentioned fix is now shipped in https://github.com/yireo/Yireo_Webp2/releases/tag/0.4.1

Unfortunately, I can't duplicate the first issue. There seems nothing wrong with the HTML. The only thing I could say is that the extension is unable to convert this image(s) to WebP. You mention that the `cwebp` binary on your system is able to fix this. The extension however uses a version that is shipped in `vendor/rosell-dk/webp-convert/src/Converters/Binaries`. Could you use the binary `vendor/rosell-dk/webp-convert/src/Converters/Binaries/cwebp-linux` to test conversion?

**Comment by jissereitsma** [comment]
I'm closing this issue for now. Feel free to re-open if you think this issue still applies.
