### ISSUE TITLE
Lazy Load + Webp

### ISSUE THREAD

**Issue by webamondo** [yireo/Yireo_Webp2#7]
Hello

Your module is working great, however I don't think it's working correctly with lazy loaded images, or at least not with the magepal module I'm using. Do you know of anyway to ensure that images that are lazy loaded are also loaded as webp?

**Comment by jissereitsma** [comment]
The core doesn't ship with lazy loading of images. So, some custom solution is needed. Because the browser doesn't support lazy loading based on just CSS or HTML, JavaScript is needed. So the custom solution needs JavaScript. In that custom solution, most likely, JPG and PNGs are targetted specifically. The question is maybe whether WebP should implement a feature like lazy loading, but the WebP extension its purpose is to implement WebP images, not to implement graphical effects like lazy loading. To me, it makes much more sense to ask the builders of a lazy loading image solution why they say "image" (which should support all image formats like JPG, PNG, GIF and WebP) why there extension does not work with WebP. In short, you are addressing an issue with a custom extension that requires an additional custom solution. There is no generic solution for a custom problem.

**Comment by webamondo** [comment]
Maybe an example would help me explain myself more, if you look at this link https://www.notinthedoghouse.co.uk/shop-by-brand/mcadams-dog-food.html you will see the first 8 images are webp, the lazy load module is set to show the first 8 images and then lazy load from there on. Images 9 to 13 on the catalog grid are then not webp. Does your module only look for the images on initial load?

**Comment by jissereitsma** [comment]
I'm not sure if I understand the reason why you are opening this issue: I tried to make it clear that this is NOT a bug in our extension, because our extension supports the Magento core and the Magento core does NOT have any kind of lazy loading. You are asking whether this module only looks for images on the initial load? Yes, but this is a completely logical answer because Magento does not support a concept like "a secondary load" (which you suggest if you mention "initial load").

Are we talking about this in a theoretical way? Because if we are, let's talk about the code instead of the general circumstances: Let's talk about the specific technique that your site is using and see how this should lead into generic solutions like swapping images. Without the code stuff and without technical details, this is not a developer discussion, but almost like a merchant request a free call for issues following customization. Could you explain how (please only in technical terms) how this specific lazy loading technique is loaded and how you personally think a generic approach in our extension is able to support this?

If we can't make this a technical discussion, I think the topic should change: Instead, you would be asking whether some volunteer could step and integrate the specific Yireo WebP extension with another specific extension X. But please fill in as detailed as you can what this X actually stands for.

**Comment by webamondo** [comment]
Sorry if I have caused offence, to clarify I'm not saying it is a bug, but reading your readme I think suggested to open an issue for support.

I think webp + lazyload would be a great feature to have and I'm willing to help to get it working.

My initial comment was to see if you had webp + lazyload working at any point via some other method.

I'm not a merchant, that was just an example, maybe we close this ticket until I've worked out how the two modules work together

**Comment by jissereitsma** [comment]
Ok, no problem. And no offence taken. But again, because Magento does not support lazy loading, it depends a 100% on the mechanism that is used by the extension providing lazy loading on how to answer this question. There is no general extension procedure for adding lazy loading, there are only specific extensions doing this. And this also means that the "working together of modules" does not relate to a generic Magento procedure of fixing this, but on a specific troubleshooting of how the lazy loading works in the extension of your specific choice. It starts with details, before we can get to further details. Without the details, I would say just say "it does not work because of unknown reasons".

**Comment by kennedyabitbol** [comment]
Would be a great feature! yireo webp + yireo lazyloading ;)
