### ISSUE TITLE
Enable support for Magento 2.4.x

### ISSUE THREAD

**Issue by dehaan-jeroen** [yireo/Yireo_Webp2#71]
Currently this module depends on magento/framework 100.3.x. Please allow magento/framework 100.4.x to allow usage in Magento 2.4.x installations.

**Comment by jissereitsma** [comment]
I think you are mistaking - in two different ways actually. 

1) You have made a typo as referring to framework `100.3.x` and `100.4.x`. Both versions are outdated, because referring to Magento 2.0. I assume you wanted to mention `103.x.x` and `104.x.x` instead. See the next point.

2) The `composer.json` of this Magento module mentions the following requirement for the framework: `^101.0.1|^101.1|^102.0|^103.0`. Currently, Magento 2.4.2 ships with the framework version 103.0.2. I've seen the module being installed in numerous Magento 2.4.2 sites already. And it works without problems.

Apart from the typos, I think you are jumping to conclusions on the actual problem that you have. Perhaps, if you are facing a composer error, it is worth sharing that actual error?

**Comment by dehaan-jeroen** [comment]
Right... turns out I need to get my glasses checked. I was working in the wrong folder. Consider this issue to be non-existing.

**Comment by jissereitsma** [comment]
:)
