### ISSUE TITLE
WebP is not supported by GD

### ISSUE THREAD

**Issue by spellmen** [yireo/Yireo_Webp2#8]
Hi,
Thank you for this module. 
I installed Yireo_Webp2 extension in my local and server. It works fine in both, but some places I couldn't get the exact results.

Issues,
1.
![Screen Shot 2019-08-22 at 9 43 38 PM](https://user-images.githubusercontent.com/27009837/63531384-0849e380-c526-11e9-9b9a-38af32875ca3.png)
In my local, it shows this warning message **WebP is not supported by GD** but in the server, it's not showing that message.
I think I missed to install the **WebP** extension.  How to install it?
My system config,
Mac OS
PHP 7.2
Magento version 2.3.1

2. The actual result should come like this,
![Screen Shot 2019-08-22 at 9 51 49 PM](https://user-images.githubusercontent.com/27009837/63531896-28c66d80-c527-11e9-9d44-22ef87be3df9.png)

In some places I am getting only image tag with webp image format, but picture and source tags are missing.
![Screen Shot 2019-08-22 at 9 54 32 PM](https://user-images.githubusercontent.com/27009837/63532056-78a53480-c527-11e9-91e5-be4b31edd8d4.png)

Thanks in advance.

**Comment by jissereitsma** [comment]
You say that your system config is PHP 7.2 but the screenshot shows PHP 7.1. In any case, just install all possible PHP modules that are available on your platform. ImageMagick and GD are part of this. I'm afraid that I have neither a MacOS nor an environment where this fails, so this really is something related to your hosting setup, not this module.

**Comment by jissereitsma** [comment]
As for the second issue, you say that in "some" cases, you get no `picture` elements but images. How do you troubleshoot this? In the dynamic DOM of your browser debugger or the actual HTML source? And what is "some"? In any case, do make sure to read this (https://github.com/yireo/Yireo_Webp2/blob/master/USAGE.md because the `picture` trick is just one of the tricks and it absolutely does not work for the Fotorama effect, hence another approach is used there. I don't think this is a bug, but simply documentation overlooked. But still, I'm curious what "som" means and how you troubleshooted this. Please note that your HTML source and the live DOM of the same HTML are not (!) the same thing!

**Comment by jissereitsma** [comment]
Closing this issue. Feel free to re-open if needed.
