### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by drinkingsouls** [yireo/Yireo_Webp2#82]
Magento 2.4.2
When running bin/magento setup:di:compile

Uncaught Error: Interface 'Yireo\NextGenImages\Convertor\ConvertorInterface' not found in /home/storm/sites/designacake-co-uk/public/app/code/Yireo/Webp2/Convertor/Convertor.php:17

What could be causing this?
Thank you.

**Comment by jissereitsma** [comment]
Could you please follow https://github.com/yireo/Yireo_Webp2/blob/master/INSTALL.md ? You are not using `composer`. Do NOT skip composer if you are not understanding the goal of dependency management. By skipping composer, you are NOT making it easier for yourself, you are making it more difficult. Plus you are asking for support for a procedure that is not supported. I'm closing this issue right away because there is no issue. You simply skipped the only installation procedure that makes sense. 

For reference, https://github.com/yireo/Yireo_Webp2/blob/master/composer.json#L22

**Comment by drinkingsouls** [comment]
I can confirm that I did follow the install document and I did try installing via composer initially but that also did not work due to composer dependencies, hence why I attempted a manual install. Composer has issues with  magento/magento2-functional-testing-framework locks. I will source a different module.

**Comment by jissereitsma** [comment]
Not using composer actually will get you further from home. It sounds like you would get issues with any `composer` command from now on, including core upgrades. Are you using the Magento 2 Functional Testing Framework? Then you might need to tune that specific line in the `composer.json` file? Are you not using the Magento 2 Functional Testing Framework? Then you might simply remove the line.

**Comment by drinkingsouls** [comment]
I managed to install this using --ignore-platform-reqs in composer. It seems I opened a can of worms with the magento2-functional-testing-framework so I'm ignoring that (for now).

Module seems to working fine on category and product pages. It's pretty much ground my site to a halt at the moment. Am I to presume this is normal as it processes my entire media catalog? We have a lot of images so it may just take some time?

Thank you.

**Comment by drinkingsouls** [comment]
This is really slowing down my site, look at the resource usage!
[https://i.ibb.co/cL47Bvc/cpu.jpg](url)
Whenever I click a category or product I've not visited since installing this module it takes just short of 30 seconds to load and the process spikes.
Is this normal behaviour? Will this calm down once the webp images have all been generated?
Thank you.

**Comment by jissereitsma** [comment]
Sure, this will calm down after all WebP images have been generated. Please see the docs, which state that a WebP image is generated when it does not exist yet. It is not regenerated, unless a JPEG exists. Please also note that it depends on your platform whether `cwebp` is slow or not. Either, generate images using another generator. Or see the following https://github.com/yireo/Yireo_Webp2/issues/77 But make sure to invest time into this. Because if this would a no-brain solution, it might have been included in the core. Instead, it requires a developer mode to proactively think what could be the issue. Your `ps` shows not our extension, not PHP, but `cwebp` to be time-consuming - but anyone could do the math of 100.000 images being converted to be CPU-intensive, correct?

**Comment by jissereitsma** [comment]
Please reopen this issue if there is an installation issue. Or if you have another issue, feel free to open another issue. This issue is as of yet closed, because the original issue was closed.
