### ISSUE TITLE
 After updating 0.11.1 from 10.4, webpi not generating

### ISSUE THREAD

**Issue by HelalPatwary** [yireo/Yireo_Webp2#90]
After updating Yireo_Webp2  0.11.1 from 10.4, showing only PNG and JPEG images webpi not generating. Which was generated before at 0.10.4 and was working properly

**Comment by jissereitsma** [comment]
I assume `webpi` is a typo for WebP and with 10.4 you meant to refer to `0.10.4`? From the https://github.com/yireo/Yireo_Webp2/blob/master/CHANGELOG.md you can see that the current module requires another module as well. Are you sure you have installed all of this by using composer? Copying files to `app/code/` is definitely not supported, unless you know what you are doing.

**Comment by HelalPatwary** [comment]
I have installed all of this by using composer. And the previous version was 0.10.4 where everything works properly.But after updating it to 0.11.0 it only showing <img> tag not <picutre> tag.

**Comment by jissereitsma** [comment]
Thanks. So can you confirm that Yireo_Webp2 is at 0.11.0 or higher and that Yireo_NextGenImages is at 0.2.0 or higher and that both modules are enabled, not only in your `app/etc/config.php` but also via their setting in the Store Configuration. Could you post screenshots of the configuration values. Could you post a URL so I can confirm this is not working? Which Magento version is this? Could you point to a specific URL where a JPG is showing but a WebP should be showing?

**Comment by emirajbbd** [comment]
On behalf of @HelalPatwary , I am going to share you some info.
Here is how we installed the module https://devdarter.harriswebworks.com/pub/media/2021-08-11_2150.png
Here you can see webp2 module version https://devdarter.harriswebworks.com/pub/media/2021-08-11_2154.png
Here you can see NextGenImages module version https://devdarter.harriswebworks.com/pub/media/2021-08-11_2154_001.png

Here is frontend URL
https://devdarter.harriswebworks.com/maidpro/

**Comment by emirajbbd** [comment]
https://devdarter.harriswebworks.com/pub/media/2021-08-11_2211.png
https://devdarter.harriswebworks.com/pub/media/2021-08-11_2212.png
https://devdarter.harriswebworks.com/pub/media/2021-08-11_2212_001.png

**Comment by jissereitsma** [comment]
Thanks. The images you posted are showing that both modules are correctly installed and all settings are fine. I assume that all screenshots apply to the same Magento instance https://devdarter.harriswebworks.com/ . If not, please post the URL of the Magento instance that has issues. 

On the homepage https://devdarter.harriswebworks.com/default/ I can see the following logo: https://devdarter.harriswebworks.com/pub/media/logo/websites/1/darter-footer-logo.png I am able to see that a WebP variant of this image exists: https://devdarter.harriswebworks.com/pub/media/logo/websites/1/darter-footer-logo.webp Also that WebP image is smaller, so should be showing correctly without issues. I'm not seeing a reason why this would not work.

Again, some confirmation: Could you confirm that this site is running the Developer Mode (because it is in development)? Could you also confirm that all caches were cleaned while checking the result? I can also see in the HTTP headers that the Full Page Cache is hit. Could you disable the Full Page Cache (or perhaps all caches) to confirm the results are not coming from a cache?

**Comment by emirajbbd** [comment]
I tested on both developer and production mode, disabling all the cache but no luck.
If you want I can share you full access of the site (SFTP and Admin Details). Then I need you to send me an email address

**Comment by jissereitsma** [comment]
If this was a paid extension, I would indeed go all the way to get to the bottom of this. But as of yet, no one else is reporting an issue like this, and I'm unable to duplicate the issue myself. Therefore, the issue seems really specific to your environment. 

Could you confirm that https://devdarter.harriswebworks.com/default/ is a development site? If so, please turn on the Developer Mode and turn off all caches, and let me inspect the HTML again. If this is not a development site, could you provide one? Currently, I can see that the Production Mode is again active.

**Comment by emirajbbd** [comment]
Ok I just enabled developer mode and disabled all the cache https://devdarter.harriswebworks.com/pub/media/2021-08-11_2322.png

Man this is not only the one site, We are using your module for at least 20 community version and 3 commerce version. All have same issue. I had to downgrade your module on the production sites to make them functional.  Here is a magento commerce which works fine with lower version https://thesolarbizdev.harriswebworks.com/ . See here one another magento commerce https://www.accustandard.com/ which even works with cdn(I had to write a small plugin)

**Comment by jissereitsma** [comment]
Thanks. It strikes me that earlier the homepage was showing products, but now that the caches are disabled and the Developer Mode turned on, there is no content on the homepage anymore. There is no categories menu and via search I'm unable to see any product. Could this be part of the issue?

The only image that I'm able to find is the logo. There is a WebP variation though. So I'm still not understanding why the picture tag would not show.

Another confirmation: Could you state the PHP version, Magento version and the type of operating system / platform (Linux, Windows, etc)?

And: I can see that the URLs for static assets all have `pub/` in their name, proofing that the DocumentRoot is changed dangerously into the Magento root instead of its `pub/` subfolder. Could you try changing the DocumentRoot to `pub/` to see if that changes anything?

**Comment by emirajbbd** [comment]
I wanted to share you admin and sftp, You need not deep dive to detect the problem but it could answer you all. Actually it is a B2B site, has a lot of stores like https://devdarter.harriswebworks.com/maidpro/, https://devdarter.harriswebworks.com/aireserv855/ etc

All the site have same Magento 2.4.2 or 2.4.3 , PHP 7.4 , Centos 8, 
Just updated Document Root to pub/

Here is the live site running with lower version of your module https://www.dartergroup.com/maidpro/
Still I am ready to share access

**Comment by emirajbbd** [comment]
If it helps https://devdarter.harriswebworks.com/media/2021-08-12_0059.png

**Comment by jissereitsma** [comment]
Thanks for the additional details. Unfortunately, we have reached a point where exchanging further details doesn't help indeed. There is something specific in your environment, and code debugging is needed to get to the bottom of this. It is my experience that this takes easily one hour, perhaps more. And to be efficient in this, so that it takes only this amount of time, a local source is needed so that something like XDebug could be used. SFTP is out of the question: It would mean that `die()` statements are added to files, those files are uploaded and the processes is repeated endlessly in the hope that it delivers something in time. Usually, I would ask for the complete sources of the Magento site plus a dump of the Magento database, so that things can be setup locally. Setting up that instance locally usually takes another hour - including the exchange of data, the download and everything else. In other words, we are talking about hours of support.

I have mentioned the word *unfortunately*. Because this is not something I'm able to offer. I already volunteered to create the extension for free and maintain it for years. I volunteered to give best effort support. But because this issue is site-specific, and not reproducable by anyone else (yet), I'm not going to volunteer to fix this. My listing of other voluntary tasks is simply too large. And to be fair to the rest of the community, I will need to move this request to the bottom of that voluntary list. Which is huge.

Open source means that everyone puts effort into issues like this. I assume you are a developer and you are familiar with Xdebug and code debugging. In the end a function like https://github.com/yireo/Yireo_NextGenImages/blob/b31a4c86f1b997393ea72fb1230e5ea89b1b4d64/Image/HtmlReplacer.php#L89 needs to be called. But for some reasons it is not. I'm happy to collaborate on this. But unfortunately, I'm unable to comply to your request to fix this in the way you want, simply because I don't think it is a general issue, I'm unable to reproduce it anywhere else (yet) and because I'm not the owner of the projects where this problem occurs. I hope you understand.
