### ISSUE TITLE
webp image is not be upload on editor and product image upload

### ISSUE THREAD

**Issue by moazzama** [yireo/Yireo_Webp2#93]
magento 2 disallowed file and is not be be upload

**Comment by jissereitsma** [comment]
Correct. That's also not what this extension is about. For the issue that Magento doesn't upload WebP in its WYSIWYG editor, please open an issue in the Magento repository instead (not this extension). As a workaround, just upload a JPG and PNG, and use this extension to convert that image automatically to WebP.

Closing this ticket because it is a reference to a missing core feature, not a feature of this extension.
