### ISSUE TITLE
Unsupported GIF

### ISSUE THREAD

**Issue by manojxumulus** [yireo/Yireo_Webp2#95]
Hello 

we are having an issue with the Unsupported file type https://prnt.sc/1qfb686 strangely it seems an issue is with the Magento loader gif as we don't have any other gif on the page.

Please do let me know if you need anything else.

Thanks

**Comment by jissereitsma** [comment]
Thanks for reporting this. Which versions are the NextGenImages module and the WebP2 module? This was supposed to be fixed a few versions back already.

**Comment by manojxumulus** [comment]
Hello jisse,

Thanks for your instant support

we have below version of both the extension

"name": "yireo/magento2-next-gen-images",
"license": "OSL-3.0",
"version": "0.2.3",

"name": "yireo/magento2-webp2",
"license": "OSL-3.0",
"version": "0.10.10",

Thanks

**Comment by jissereitsma** [comment]
Thanks. Since WebP2 0.10.10 numerous releases were made already. Could you upgrade to the latest versions first?

**Comment by manojxumulus** [comment]
Okay sure let me upgrade it and get back to you Thanks

**Comment by jissereitsma** [comment]
Please note that this is open source, free and based on voluntary work. In most, if not all cases, where you would be filing an issue on such an open source project, it is assumed that you are doing already everything you can to troubleshoot things. And upgrading to the latest version, to prevent reporting issues that were fixed ages ago, is actually step number one.

I'm closing this issue because it was not related to the latest version.

If you experience a new issue, please make sure to go through the support docs first.
